name: CloudFoundry Pipeline for MTAs - Workflow Edition
resources:
  containers:
  - container: mta
    image: 'ppiper/mta-archive-builder:latest'
    options: --user 0:0
  - container: cfcli
    image: 'ppiper/cf-cli'
    options: --user 0:0 --privileged
  - container: node
    image: 'geekykaran/headless-chrome-node-docker:latest'
    options: --privileged

stages:
- stage: build
  displayName: Build MTA for Workflow Approuter
  jobs:
    - job: build
      pool:
        vmImage: 'ubuntu-latest'
      container: mta
      steps:          
        - bash: 'mtaBuild --build-target CF --mtar $(Build.Repository.Name).mtar build'
        - publish: $(System.DefaultWorkingDirectory)/.
          artifact: WebApp

- stage: atm_deploy
  displayName: Deployment to PWC SCP CF Env 
  jobs:
    - job: deploy
      pool:
        vmImage: 'ubuntu-latest'
      container: cfcli
      steps:
        - download: current
          artifact: WebApp
        - bash: 'cf login -u "$(CF-USER)" -p "$(CF-PASSWORD)" -a "$(CF-API)" -o "$(CF-ORG)" -s "$(CF-SPACE)" && cf deploy $(Pipeline.Workspace)/WebApp/$(Build.Repository.Name).mtar -f'